[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Authorization, X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Request-Method"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "https://pmasquiaran.dev"
    #Cache-Control = "public, max-age=604800"
    Content-Security-Policy = "default-src 'self'; script-src 'unsafe-inline' 'self' https://www.googletagmanager.com/gtag/ https://cdnjs.cloudflare.com/; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com/ https://cdnjs.cloudflare.com/; object-src 'none'; base-uri 'self'; connect-src 'self' https://www.google-analytics.com/g/; font-src 'self' https://fonts.gstatic.com/; form-action 'self'; frame-src 'self'; img-src 'self'; media-src 'self' data: *;"

    Permissions-Policy = "geolocation=(), microphone=(), midi=(), sync-xhr=() ,accelerometer=(), gyroscope=(), magnetometer=(), camera=(), fullscreen=(self)"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; preload"
    X-Content-Security-Policy = "allow 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-Permitted-Cross-Domain-Policies = "master-only"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/portafolio/osborn/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/portafolio/udec/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"