[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Headers = "Authorization, X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Allow-Request-Method"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Origin = "https://pmasquiaran.dev"
    Cache-Control = "public, max-age=0"
    Content-Security-Policy = "base-uri 'self'; default-src 'self'; img-src 'self'; media-src 'self' data: *; form-action 'self';"
    Permissions-Policy = "geolocation=(), microphone=(), midi=(), sync-xhr=() ,accelerometer=(), gyroscope=(), magnetometer=(), camera=(), fullscreen=(self)"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; preload"
    X-Content-Security-Policy = "allow 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-Permitted-Cross-Domain-Policies = "master-only"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/portafolio/osborn/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/portafolio/udec/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"