[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'unsafe-eval' 'unsafe-inline' 'self' https://cdnjs.cloudflare.com/ https://www.gstatic.com/recaptcha/releases/ https://www.googletagmanager.com/gtag/; style-src 'unsafe-inline' 'self' https://fonts.googleapis.com https://maxcdn.bootstrapcdn.com; object-src 'none'; base-uri 'self'; connect-src 'self' https://www.google-analytics.com/g/; font-src 'self' https://fonts.gstatic.com https://maxcdn.bootstrapcdn.com; form-action 'self'; frame-src 'self' https://cdnjs.cloudflare.com/; img-src 'self'; media-src 'self' data: *;"
    Feature-Policy = "camera 'none'; display-capture 'none'; document-domain 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'"
    Permissions-Policy = "geolocation=(), microphone=(), midi=(), sync-xhr=() ,accelerometer=(), gyroscope=(), magnetometer=(), camera=(), fullscreen=(self)'"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Security-Policy: "allow 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-Permitted-Cross-Domain-Policies = "master-only"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/portafolio/osborn/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/portafolio/udec/images/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/css/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/js/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"